[package]
name = "oxidera1n"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = {version = "4.5.20", features = ["cargo"]}
rusty_libimobiledevice = {version = "0.2.0", features = ["dynamic"]}
owo-colors = "3"